stages:
  - build
  - test

build_job:
  stage: build
  script:
    - docker build -t demo-img .
    - docker save demo-img > demo-img.tar
  artifacts:
    paths:
      - demo-img.tar

test_job:
  stage: test
  script:
    - docker load < demo-imge.tar
    - docker run demo-img > output.txt
    - grep "سلام از GitLab CI/CD!" output.txt
